- name: Install elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Template elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0640

- name: Ensure Elasticsearch is started and enabled
  service:
    name: elasticsearch
    state: started
    enabled: yes